packages:
  - packages/*
  - apps/*
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@incubateur-ademe/nosgestesclimat'
onlyBuiltDependencies:
  - msw
  - prisma
injectWorkspacePackages: true
