packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - core-js
  - core-js-pure
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver

injectWorkspacePackages: true
#minimumReleaseAge: 10080 # 7 days

minimumReleaseAgeExclude:
  - '@incubateur-ademe/nosgestesclimat'

onlyBuiltDependencies:
  - '@incubateur-ademe/nosgestesclimat'
  - '@nosgestesclimat/core'
  - '@prisma/engines'
  - '@sentry/cli'
  - msw
  - prisma

nodeLinker: hoisted
