name: 'Setup Playwright and App'
description: 'Sets up dependencies and installs Playwright'
inputs:
  browser:
    description: 'Browser to install'
    required: true
    default: 'chromium'
runs:
  using: 'composite'
  steps:
    - name: Setup
      uses: ./.github/actions/setup

    - name: Install Playwright
      shell: bash
      working-directory: ./apps/site
      env:
        DEBUG: pw:*
      run: timeout 1000 pnpm playwright install ${{ inputs.browser }} ${{ inputs.browser == 'webkit' && '--with-deps' || '' }}
