name: Deploy

on:
  push:
    branches:
      - preprod
      - main

jobs:
  deploy-preprod:
    name: Deploy to Scalingo (preprod)
    runs-on: ubuntu-latest
    environment: Preprod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Scalingo
        uses: ./.github/actions/deploy-scalingo
        with:
          scalingo-api-token: ${{ secrets.SCALINGO_API_TOKEN }}
          scalingo-app-name: ${{ vars.SCALINGO_APP_NAME }}
          git-ref: preprod
          git-repo: ${{ github.repository }}


  e2e-preprod:
    needs: deploy-preprod
    uses: ./.github/workflows/e2e.yaml
    with:
      is_preprod: true
    secrets:
      MAILISK_API_KEY: ${{ secrets.MAILISK_API_KEY }}

  deploy-main:
    name: Deploy to Scalingo (main)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: e2e-preprod
    environment: Prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Scalingo
        uses: ./.github/actions/deploy-scalingo
        with:
          scalingo-api-token: ${{ secrets.SCALINGO_API_TOKEN }}
          scalingo-app-name: ${{ vars.SCALINGO_APP_NAME }}
          git-ref: main
          git-repo: ${{ github.repository }}
